// SPDX-License-Identifier: AGPL-3.0-or-later

// Command gen-config-reference renders the human-readable configuration reference from the
// versioned JSON Schema. The schema remains authoritative; CI uses -check to prevent drift.
package main

import (
	"bytes"
	"encoding/json"
	"flag"
	"fmt"
	"os"
	"path/filepath"
	"sort"
	"strings"
)

const (
	schemaPath = "schemas/config.v1.schema.json"
	outputPath = "docs/configuration.md"
)

type row struct {
	Path        string
	Type        string
	Required    bool
	Default     string
	Constraints string
	Description string
}

func main() {
	check := flag.Bool("check", false, "fail if docs/configuration.md is not current")
	flag.Parse()

	generated, err := generate()
	if err != nil {
		fatal(err)
	}
	if *check {
		current, readErr := os.ReadFile(outputPath)
		if readErr != nil {
			fatal(fmt.Errorf("read %s: %w", outputPath, readErr))
		}
		if !bytes.Equal(current, generated) {
			fatal(fmt.Errorf("%s is stale; run go run ./hack/gen-config-reference.go", outputPath))
		}
		return
	}
	// #nosec G306 -- generated documentation is intentionally readable in source checkouts and
	// contains only public schema metadata, never configuration or resolved secret values.
	if err = os.WriteFile(outputPath, generated, 0o644); err != nil {
		fatal(fmt.Errorf("write %s: %w", outputPath, err))
	}
}

func generate() ([]byte, error) {
	raw, err := os.ReadFile(schemaPath)
	if err != nil {
		return nil, fmt.Errorf("read %s: %w", schemaPath, err)
	}
	var schema map[string]any
	if err = json.Unmarshal(raw, &schema); err != nil {
		return nil, fmt.Errorf("decode %s: %w", schemaPath, err)
	}

	rows := make(map[string]row)
	walk(schema, schema, "", true, rows, make(map[string]bool))
	paths := make([]string, 0, len(rows))
	for path := range rows {
		if path != "" {
			paths = append(paths, path)
		}
	}
	sort.Strings(paths)

	var out strings.Builder
	out.WriteString("<!-- Generated by hack/gen-config-reference.go; do not edit by hand. -->\n")
	out.WriteString("# Configuration reference\n\n")
	out.WriteString("This reference is generated from [`schemas/config.v1.schema.json`](../schemas/config.v1.schema.json), which is authoritative. Regenerate it with `go run ./hack/gen-config-reference.go`. Veduta loads `veduta.yaml` and then merges sibling `conf.d/*.yaml` files in lexical order; later values replace earlier values and arrays replace as a whole.\n\n")
	out.WriteString("Unknown fields are rejected. A required field can still be conditional on a selected mode or runtime; the schema and `veduta --check-config` enforce those conditions. Paths containing `<name>` are maps keyed by an operator-chosen ID, and `[]` denotes an array item.\n\n")
	out.WriteString("| Path | Type | Required | Default | Constraints | Description |\n")
	out.WriteString("| --- | --- | --- | --- | --- | --- |\n")
	for _, path := range paths {
		r := rows[path]
		fmt.Fprintf(&out, "| `%s` | %s | %s | %s | %s | %s |\n",
			escape(r.Path), escape(r.Type), yesNo(r.Required), valueOrDash(r.Default),
			valueOrDash(r.Constraints), valueOrDash(r.Description))
	}
	out.WriteString("\nSecret-bearing values use `${secret:NAME}`. Veduta resolves `/run/secrets/NAME` first and then the process environment variable `NAME`; secret values should never be written directly into configuration.\n")
	return []byte(out.String()), nil
}

func walk(root, schema map[string]any, path string, required bool, rows map[string]row, active map[string]bool) {
	if ref, ok := schema["$ref"].(string); ok {
		key := path + "\x00" + ref
		if active[key] {
			return
		}
		resolved := resolve(root, ref)
		if resolved == nil {
			return
		}
		active[key] = true
		mergeRow(rows, makeRow(path, schema, required))
		walk(root, resolved, path, required, rows, active)
		delete(active, key)
		return
	}

	mergeRow(rows, makeRow(path, schema, required))
	for _, keyword := range []string{"oneOf", "anyOf", "allOf"} {
		for _, alternative := range objectList(schema[keyword]) {
			walk(root, alternative, path, required, rows, active)
		}
	}

	requiredNames := stringSet(schema["required"])
	if properties, ok := schema["properties"].(map[string]any); ok {
		names := make([]string, 0, len(properties))
		for name := range properties {
			names = append(names, name)
		}
		sort.Strings(names)
		for _, name := range names {
			child, ok := properties[name].(map[string]any)
			if !ok {
				continue
			}
			walk(root, child, join(path, name), requiredNames[name], rows, active)
		}
	}
	if additional, ok := schema["additionalProperties"].(map[string]any); ok {
		walk(root, additional, join(path, "<name>"), false, rows, active)
	}
	if items, ok := schema["items"].(map[string]any); ok {
		walk(root, items, path+"[]", false, rows, active)
	}
}

func makeRow(path string, schema map[string]any, required bool) row {
	return row{
		Path: path, Type: schemaType(schema), Required: required,
		Default: jsonValue(schema["default"]), Constraints: constraints(schema),
		Description: textValue(schema["description"]),
	}
}

func mergeRow(rows map[string]row, incoming row) {
	if incoming.Path == "" {
		return
	}
	existing, ok := rows[incoming.Path]
	if !ok {
		rows[incoming.Path] = incoming
		return
	}
	existing.Type = union(existing.Type, incoming.Type)
	existing.Required = existing.Required || incoming.Required
	if existing.Default == "" {
		existing.Default = incoming.Default
	}
	existing.Constraints = union(existing.Constraints, incoming.Constraints)
	if existing.Description == "" {
		existing.Description = incoming.Description
	}
	rows[incoming.Path] = existing
}

func schemaType(schema map[string]any) string {
	if ref, ok := schema["$ref"].(string); ok {
		return strings.TrimPrefix(filepath.Base(ref), "#")
	}
	if value, ok := schema["const"]; ok {
		return "constant " + jsonValue(value)
	}
	if values, ok := schema["enum"].([]any); ok {
		parts := make([]string, 0, len(values))
		for _, value := range values {
			parts = append(parts, jsonValue(value))
		}
		return strings.Join(parts, " | ")
	}
	if value, ok := schema["type"].(string); ok {
		return value
	}
	for _, keyword := range []string{"oneOf", "anyOf"} {
		var types string
		for _, alternative := range objectList(schema[keyword]) {
			types = union(types, schemaType(alternative))
		}
		if types != "" {
			return types
		}
	}
	return "object"
}

func constraints(schema map[string]any) string {
	keys := []string{"minimum", "maximum", "minLength", "maxLength", "minItems", "maxItems", "uniqueItems", "pattern", "format"}
	parts := make([]string, 0, len(keys)+1)
	for _, key := range keys {
		if value, ok := schema[key]; ok {
			parts = append(parts, key+"="+jsonValue(value))
		}
	}
	if rules, ok := schema["allOf"].([]any); ok && len(rules) > 0 {
		parts = append(parts, fmt.Sprintf("%d conditional rule(s)", len(rules)))
	}
	return strings.Join(parts, "; ")
}

func resolve(root map[string]any, ref string) map[string]any {
	if !strings.HasPrefix(ref, "#/") {
		return nil
	}
	var current any = root
	for _, part := range strings.Split(strings.TrimPrefix(ref, "#/"), "/") {
		part = strings.ReplaceAll(strings.ReplaceAll(part, "~1", "/"), "~0", "~")
		object, ok := current.(map[string]any)
		if !ok {
			return nil
		}
		current = object[part]
	}
	resolved, _ := current.(map[string]any)
	return resolved
}

func objectList(value any) []map[string]any {
	items, _ := value.([]any)
	result := make([]map[string]any, 0, len(items))
	for _, item := range items {
		if object, ok := item.(map[string]any); ok {
			result = append(result, object)
		}
	}
	return result
}

func stringSet(value any) map[string]bool {
	result := make(map[string]bool)
	items, _ := value.([]any)
	for _, item := range items {
		if name, ok := item.(string); ok {
			result[name] = true
		}
	}
	return result
}

func join(parent, child string) string {
	if parent == "" {
		return child
	}
	return parent + "." + child
}

func union(left, right string) string {
	if left == "" {
		return right
	}
	if right == "" || left == right {
		return left
	}
	parts := strings.Split(left, " | ")
	for _, part := range parts {
		if part == right {
			return left
		}
	}
	return left + " | " + right
}

func jsonValue(value any) string {
	if value == nil {
		return ""
	}
	encoded, err := json.Marshal(value)
	if err != nil {
		return ""
	}
	return string(encoded)
}

func textValue(value any) string {
	text, _ := value.(string)
	return text
}

func escape(value string) string {
	value = strings.ReplaceAll(value, "|", "\\|")
	return strings.Join(strings.Fields(value), " ")
}

func valueOrDash(value string) string {
	if value == "" {
		return "—"
	}
	return escape(value)
}

func yesNo(value bool) string {
	if value {
		return "yes"
	}
	return "no"
}

func fatal(err error) {
	fmt.Fprintln(os.Stderr, "gen-config-reference:", err)
	os.Exit(1)
}
