// SPDX-License-Identifier: AGPL-3.0-or-later

//go:build ignore

// Command gen-third-party-notices renders THIRD-PARTY-NOTICES.md, the user-facing attribution
// document for the code Veduta actually ships.
//
// It is deliberately separate from THIRD-PARTY-LICENSES.md. That file is a contributor-facing
// policy record: every Go module in go.mod, curated by hand, with a justification per dependency,
// so adding one is a deliberate act. This file is the user-facing artefact required by the licences
// of the code we actually ship, and it is generated so it cannot drift:
//
//   - frontend: web/bundled-packages.json, written by web/scripts/bundled-packages.mjs from
//     Rollup's real module graph - what ends up inside the bundle, not what package.json declares.
//   - WebAssembly plugins: the normal-dependency closure of each shipped crate, from
//     `cargo metadata`. Conservatively includes proc-macro crates, which run at build time rather
//     than being linked into the module; over-disclosure is the safe direction here.
//   - Go: the curated tables in THIRD-PARTY-LICENSES.md, so the two documents cannot disagree.
//
// CI runs -check, so a new dependency fails the build until the notices are regenerated.
package main

import (
	"bytes"
	"encoding/json"
	"flag"
	"fmt"
	"os"
	"os/exec"
	"regexp"
	"sort"
	"strings"
)

const (
	frontendPath = "web/bundled-packages.json"
	goLicenses   = "THIRD-PARTY-LICENSES.md"
	outputPath   = "THIRD-PARTY-NOTICES.md"
	wasmTarget   = "wasm32-unknown-unknown"

	// A second, byte-identical copy: //go:embed cannot reach above its own package directory, and
	// a running instance has to be able to serve the notices without the repository present.
	// internal/notices has a test asserting the two copies match, so neither can drift alone.
	embedPath = "internal/notices/NOTICES.md"
)

// outputs is every file `generate` produces; -check verifies all of them.
var outputs = []string{outputPath, embedPath}

// Every crate reachable as a normal dependency of these is disclosed.
var rustCrates = []string{
	"plugins/jellyfin/Cargo.toml",
	"plugins/examples/hello/Cargo.toml",
	"sdk/rust/Cargo.toml",
}

type frontendPackage struct {
	Name     string  `json:"name"`
	Version  string  `json:"version"`
	License  string  `json:"license"`
	Homepage *string `json:"homepage"`
}

type entry struct{ Name, Version, License string }

type cargoMetadata struct {
	Packages []struct {
		ID      string  `json:"id"`
		Name    string  `json:"name"`
		Version string  `json:"version"`
		License *string `json:"license"`
		Source  *string `json:"source"`
	} `json:"packages"`
	Resolve struct {
		Root  string `json:"root"`
		Nodes []struct {
			ID   string `json:"id"`
			Deps []struct {
				Pkg      string `json:"pkg"`
				DepKinds []struct {
					Kind *string `json:"kind"`
				} `json:"dep_kinds"`
			} `json:"deps"`
		} `json:"nodes"`
	} `json:"resolve"`
}

func main() {
	check := flag.Bool("check", false, "fail if THIRD-PARTY-NOTICES.md is not current")
	flag.Parse()

	generated, err := generate()
	if err != nil {
		fatal(err)
	}
	if *check {
		for _, path := range outputs {
			current, readErr := os.ReadFile(path)
			if readErr != nil {
				fatal(fmt.Errorf("read %s: %w", path, readErr))
			}
			if !bytes.Equal(current, generated) {
				fatal(fmt.Errorf("%s is stale; run go run ./hack/gen-third-party-notices.go", path))
			}
		}
		return
	}
	for _, path := range outputs {
		// #nosec G306 -- an attribution document is meant to be world-readable; it contains only
		// public package names, versions and licence identifiers.
		if err = os.WriteFile(path, generated, 0o644); err != nil {
			fatal(fmt.Errorf("write %s: %w", path, err))
		}
	}
}

func generate() ([]byte, error) {
	frontend, err := readFrontend()
	if err != nil {
		return nil, err
	}
	rust, err := readRust()
	if err != nil {
		return nil, err
	}
	goModules, err := readGoLicenses()
	if err != nil {
		return nil, err
	}
	icons, err := readSourceSection("Embedded offline icon pack")
	if err != nil {
		return nil, err
	}
	artwork, err := readSourceSection("Bundled backdrop artwork")
	if err != nil {
		return nil, err
	}

	var out bytes.Buffer
	out.WriteString("# Third-party notices\n\n")
	out.WriteString("Veduta redistributes the third-party software listed here. This file is generated by\n")
	out.WriteString("`hack/gen-third-party-notices.go`; CI fails if it is stale. Veduta itself is\n")
	out.WriteString("AGPL-3.0-or-later, with the SDK, schemas, plugins and examples under Apache-2.0 -\n")
	out.WriteString("see [LICENSING.md](LICENSING.md).\n\n")
	out.WriteString("Licence identifiers are the ones each project declares. Where a project offers a choice\n")
	out.WriteString("(`MIT OR Apache-2.0`), that choice is the project's to make and is reproduced unchanged.\n\n")

	out.WriteString("## Frontend bundle\n\n")
	out.WriteString("Read from Rollup's module graph, so this is what the served JavaScript actually contains -\n")
	out.WriteString("not what `package.json` declares. Build tooling that never reaches the browser is absent by\n")
	out.WriteString("construction.\n\n")
	writeTable(&out, frontend)

	out.WriteString("\n## WebAssembly plugins\n\n")
	out.WriteString("The normal-dependency closure used to build the shipped `.wasm` modules. Proc-macro crates\n")
	out.WriteString("run during the build rather than being linked into the module; they are listed anyway,\n")
	out.WriteString("because over-disclosure is the safe direction for attribution.\n\n")
	writeTable(&out, rust)

	out.WriteString("\n## Go binary\n\n")
	out.WriteString("Mirrored from the Direct and Indirect tables in\n")
	out.WriteString("[THIRD-PARTY-LICENSES.md](THIRD-PARTY-LICENSES.md), which records why each module is\n")
	out.WriteString("present and is enforced against `go.mod` by a test in `internal/contracts`.\n\n")
	writeTable(&out, goModules)

	out.WriteString("\n## Embedded icon pack\n\n")
	out.WriteString("SVG assets compiled into the binary so that rendering a dashboard never requires reaching\n")
	out.WriteString("a CDN. Simple Icons is CC0-1.0, which waives copyright but **not** trademark rights: the\n")
	out.WriteString("brand marks it contains remain the property of their owners.\n\n")
	writeSourceTable(&out, icons)

	out.WriteString("\n## Bundled backdrop artwork\n\n")
	out.WriteString("Two paintings compiled into the binary as the Veil preset's backdrop, one per colour\n")
	out.WriteString("scheme. Both are public domain and both are shipped re-encoded - downscaled, desaturated\n")
	out.WriteString("and contrast-compressed - which a public-domain work permits without condition. Nothing\n")
	out.WriteString("here is legally required; provenance for a shipped binary asset is worth recording anyway.\n\n")
	writeSourceTable(&out, artwork)

	return out.Bytes(), nil
}

func writeTable(out *bytes.Buffer, entries []entry) {
	out.WriteString("| Package | Version | Licence |\n| --- | --- | --- |\n")
	for _, e := range entries {
		version := e.Version
		if version == "" {
			version = "—"
		}
		fmt.Fprintf(out, "| `%s` | %s | %s |\n", e.Name, version, e.License)
	}
}

// writeSourceTable is for rows whose name is prose rather than a package identifier - the icon
// pack sources already carry their own inline formatting, so wrapping them in backticks would
// nest code spans and render wrong.
func writeSourceTable(out *bytes.Buffer, entries []entry) {
	out.WriteString("| Source | Version | Licence |\n| --- | --- | --- |\n")
	for _, e := range entries {
		fmt.Fprintf(out, "| %s | %s | %s |\n", e.Name, e.Version, e.License)
	}
}

func readFrontend() ([]entry, error) {
	raw, err := os.ReadFile(frontendPath)
	if err != nil {
		return nil, fmt.Errorf("read %s (run pnpm build first): %w", frontendPath, err)
	}
	var packages []frontendPackage
	if err = json.Unmarshal(raw, &packages); err != nil {
		return nil, fmt.Errorf("parse %s: %w", frontendPath, err)
	}
	entries := make([]entry, 0, len(packages))
	for _, p := range packages {
		entries = append(entries, entry{Name: p.Name, Version: p.Version, License: p.License})
	}
	return sorted(entries), nil
}

// readRust unions the normal-dependency closure of every shipped crate. Local path packages are
// Veduta's own and are covered by LICENSING.md, not by a third-party notice.
func readRust() ([]entry, error) {
	unique := map[string]entry{}
	for _, manifest := range rustCrates {
		meta, err := cargoMeta(manifest)
		if err != nil {
			return nil, err
		}
		packages := map[string]int{}
		for i, p := range meta.Packages {
			packages[p.ID] = i
		}
		nodes := map[string]int{}
		for i, n := range meta.Resolve.Nodes {
			nodes[n.ID] = i
		}

		seen := map[string]bool{}
		stack := []string{meta.Resolve.Root}
		for len(stack) > 0 {
			id := stack[len(stack)-1]
			stack = stack[:len(stack)-1]
			if seen[id] {
				continue
			}
			seen[id] = true
			node, ok := nodes[id]
			if !ok {
				continue
			}
			for _, dep := range meta.Resolve.Nodes[node].Deps {
				if isNormalDep(dep.DepKinds) {
					stack = append(stack, dep.Pkg)
				}
			}
		}

		for id := range seen {
			index, ok := packages[id]
			if !ok {
				continue
			}
			p := meta.Packages[index]
			if p.Source == nil {
				continue // a path dependency: Veduta's own crate
			}
			if p.License == nil || *p.License == "" {
				return nil, fmt.Errorf("crate %s@%s declares no licence", p.Name, p.Version)
			}
			unique[p.Name+"@"+p.Version] = entry{Name: p.Name, Version: p.Version, License: *p.License}
		}
	}

	entries := make([]entry, 0, len(unique))
	for _, e := range unique {
		entries = append(entries, e)
	}
	return sorted(entries), nil
}

// A dependency edge with no kind is a normal one; "dev" and "build" edges are not redistributed.
func isNormalDep(kinds []struct {
	Kind *string `json:"kind"`
}) bool {
	if len(kinds) == 0 {
		return true
	}
	for _, k := range kinds {
		if k.Kind == nil {
			return true
		}
	}
	return false
}

func cargoMeta(manifest string) (*cargoMetadata, error) {
	// #nosec G204 -- manifest paths are compile-time constants in rustCrates.
	cmd := exec.Command("cargo", "metadata", "--manifest-path", manifest,
		"--format-version", "1", "--offline", "--filter-platform", wasmTarget)
	var stderr bytes.Buffer
	cmd.Stderr = &stderr
	raw, err := cmd.Output()
	if err != nil {
		return nil, fmt.Errorf("cargo metadata %s: %w: %s", manifest, err, strings.TrimSpace(stderr.String()))
	}
	var meta cargoMetadata
	if err = json.Unmarshal(raw, &meta); err != nil {
		return nil, fmt.Errorf("parse cargo metadata for %s: %w", manifest, err)
	}
	return &meta, nil
}

// Go module rows: | `module` | Licence | Why |  (Direct) or | `module` | Licence |  (Indirect).
var moduleRow = regexp.MustCompile("^\\|\\s*`([^`]+)`\\s*\\|\\s*([^|]+?)\\s*\\|")

// Icon pack rows carry a prose source name rather than a package: | Source | Version | Licence |.
var iconRow = regexp.MustCompile(`^\|\s*([^|]+?)\s*\|\s*([^|]+?)\s*\|\s*([^|]+?)\s*\|`)

// sectionsOf splits THIRD-PARTY-LICENSES.md on its "## " headings. Only the Go tables are mirrored
// from it; the frontend and Rust sets are derived from the real graphs instead, and the icon pack
// has no lockfile to derive from.
func sectionsOf(raw string) map[string][]string {
	sections := map[string][]string{}
	current := ""
	for _, line := range strings.Split(raw, "\n") {
		if strings.HasPrefix(line, "## ") {
			current = strings.TrimSpace(strings.TrimPrefix(line, "## "))
			continue
		}
		if current != "" {
			sections[current] = append(sections[current], line)
		}
	}
	return sections
}

func readGoLicenses() ([]entry, error) {
	raw, err := os.ReadFile(goLicenses)
	if err != nil {
		return nil, fmt.Errorf("read %s: %w", goLicenses, err)
	}
	sections := sectionsOf(string(raw))
	var entries []entry
	for _, name := range []string{"Direct", "Indirect"} {
		lines, ok := sections[name]
		if !ok {
			return nil, fmt.Errorf("%s: section %q not found; has its structure changed?", goLicenses, name)
		}
		for _, line := range lines {
			if match := moduleRow.FindStringSubmatch(line); match != nil {
				entries = append(entries, entry{Name: match[1], License: match[2]})
			}
		}
	}
	if len(entries) == 0 {
		return nil, fmt.Errorf("%s: no module rows found; has its table format changed?", goLicenses)
	}
	return sorted(entries), nil
}

// readSourceSection mirrors one of the curated prose-named tables in THIRD-PARTY-LICENSES.md -
// the icon pack, the backdrop paintings - into the generated notices. These are assets compiled
// into the binary and so redistributed, but no lockfile describes them, which is why the curated
// file is their source of truth rather than a resolver.
func readSourceSection(section string) ([]entry, error) {
	raw, err := os.ReadFile(goLicenses)
	if err != nil {
		return nil, fmt.Errorf("read %s: %w", goLicenses, err)
	}
	lines, ok := sectionsOf(string(raw))[section]
	if !ok {
		return nil, fmt.Errorf("%s: section %q not found", goLicenses, section)
	}
	var entries []entry
	for _, line := range lines {
		match := iconRow.FindStringSubmatch(line)
		if match == nil || match[1] == "Source" || strings.HasPrefix(match[1], "---") {
			continue
		}
		entries = append(entries, entry{Name: match[1], Version: match[2], License: match[3]})
	}
	if len(entries) == 0 {
		return nil, fmt.Errorf("%s: no rows found in %q", goLicenses, section)
	}
	return sorted(entries), nil
}

func sorted(entries []entry) []entry {
	sort.Slice(entries, func(i, j int) bool {
		if entries[i].Name != entries[j].Name {
			return entries[i].Name < entries[j].Name
		}
		return entries[i].Version < entries[j].Version
	})
	return entries
}

func fatal(err error) {
	fmt.Fprintln(os.Stderr, "gen-third-party-notices:", err)
	os.Exit(1)
}
