// SPDX-License-Identifier: AGPL-3.0-or-later

// Package notices carries the third-party attribution document so a running instance can disclose
// what it redistributes without the repository being present. AGPL section 13 already obliges us
// to offer the corresponding source over the network (internal/version carries that link); the
// licences of the code we bundle oblige us to carry their attribution with the distribution, and a
// single self-contained binary has nowhere else to put it.
//
// NOTICES.md is generated by hack/gen-third-party-notices.go, which writes the same bytes to the
// repository-root THIRD-PARTY-NOTICES.md. //go:embed cannot reach above its own package directory,
// hence the second copy; TestEmbeddedNoticesMatchRepositoryRoot keeps them identical.
package notices

import _ "embed"

//go:embed NOTICES.md
var markdown string

// Markdown returns the attribution document as CommonMark source.
func Markdown() string { return markdown }
